### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Adaptivity**
I hope you @Tombenpotter or you @TehNut can merge this.

### CODE REVIEW

**Comment by TehNut** [comment]
As I said before, there is no transfer of ownership. You are simply maintaining any official fork.

**Comment by Adaptivity** [comment]
I'm talking not about ownership transfer. Just wanted to let people know about new fork, so when people go to official repo they also can see an updated fork. Maybe you can add some kind of notice to readme?

**Comment by Dream-Master** [comment]
If you click on the number right from the fork button you see which is the latest one who adding code/stuff and can switch to the newer repro.

**Comment by fewizz** [comment]
image

**Comment by Adaptivity** [comment]
Not every person knows about Github features.

**Comment by Dream-Master** [comment]
sure that's why i mention it.

**Pull request closed without merging**
